volumes:
  vdcvol1:

services:
  vdcservice:
    image: rajchaudhuri/voxel-dockerclient:0.4.3
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - vdcvol1:/app/data
    ports:
      - 8080:8080
