version: '3.4'

volumes:
  vdcvol1:

services:
  vdcservice:
    image: rajchaudhuri/voxel-dockerclient:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - vdcvol1:/app/data
    ports:
      - 8080:8080